image: registry.timmertech.nl/docker/docker:latest

stages:
  - build
  - trigger

variables:
  CI: 'true'
  DOCKER_DRIVER: overlay2

################################################################################
# Template(s)
################################################################################
.docker-build: &docker-build
  stage: build
  before_script:
    - echo ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - docker build --pull
        --build-arg VCS_REF="${CI_COMMIT_SHORT_SHA}"
        --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
        --build-arg DOCKER_IMAGE=${DOCKER_IMAGE}
        --file=${DOCKER_FILE}
        --tag=${DOCKER_IMAGE} .

################################################################################
# Job Configuration
################################################################################
:Build:
  <<: *docker-build
  variables:
    DOCKER_FILE: Dockerfile
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  only:
    - branches
  except:
    - master
    - schedules

:Release:
  <<: *docker-build
  variables:
    DOCKER_FILE: Dockerfile
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_SLUG}
  only:
    - tags
  after_script:
    - docker push ${DOCKER_IMAGE}

:Auto-Update:
  <<: *docker-build
  variables:
    DOCKER_FILE: Dockerfile
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  only:
    - master
    - schedules
  after_script:
    - docker push ${DOCKER_IMAGE}
