default:
  image: registry.timmertech.nl/docker/docker:latest

stages:
  - build
  - dockerhub

include:
  - project: templates/ci
    file: docker.yml

.build:
  stage: build
  extends: .docker-build-amd64
  variables:
    DOCKER_PROXY: "ENABLED"

build:
  extends: .build
  variables:
    DOCKER_HUB: "ENABLED"
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_LATEST}
      --tag=${DOCKER_IMAGE_HUB}

release:
  extends: .build
  variables:
    DOCKER_HUB: "ENABLED"
    DOCKER_IMAGE: ${DOCKER_IMAGE_PATH}:${CI_COMMIT_TAG}
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:${CI_COMMIT_TAG}
  only:
    - tags
