image: registry.timmertech.nl/docker/docker:latest

stages:
  - build
  - triggers

.docker-login: &docker-login
  before_script:
    - echo ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}

.docker-build: &docker-build
  script:
    - docker build --pull --force-rm=true --squash 
        --build-arg VCS_REF=`git rev-parse --short HEAD` 
        --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` 
        --tag=${DOCKER_IMAGE} .

.docker-push: &docker-push
  after_script:
    - docker push ${DOCKER_IMAGE}

docker:latest:
  stage: build
  only: 
    - master
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  <<: *docker-login
  <<: *docker-build
  <<: *docker-push

docker:branches:
  stage: build
  only:
    - branches
  except:
    - master
    - tags
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}
  <<: *docker-login
  <<: *docker-build

docker:release:
  stage: build
  only:
    - tags
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}
  <<: *docker-login
  <<: *docker-build
  <<: *docker-push

gitlab:runner:latest:
  stage: triggers
  only:
    - master
  except:
    - tags
  script:
    - curl -s -X POST -F token=${GITLAB_RUNNER_TOKEN} -F ref=master https://gitlab.timmertech.nl/api/v4/projects/6/trigger/pipeline > /dev/null

dockerhub:latest:
  stage: triggers
  only:
    - master
  except:
    - tags
  script:
    - curl -s -H 'Content-Type:application/json' --data '{"build":true}' -X POST https://registry.hub.docker.com/u/datacore/alpine-glibc/trigger/${DOCKERHUB_TOKEN}/ > /dev/null

dockerhub:release:
  stage: triggers
  only:
    - tags
  before_script:
    - apk add --update --no-cache curl
  script:
    - curl -s -H 'Content-Type:application/json' --data "{\"source_type\":\"Tag\",\"source_name\":\"${CI_COMMIT_REF_NAME}\"}" -X POST https://registry.hub.docker.com/u/datacore/alpine-glibc/trigger/${DOCKERHUB_TOKEN}/ > /dev/null


#alpine:golang:
#  stage: triggers
#  except:
#     - tags
#   before_script:
#     - apk add --update --no-cache curl
#   script:
#     - curl -X POST -F token=$CI_BUILD_TOKEN -F ref=master https://gitlab.timmertech.nl/api/v3/projects/19/trigger/builds > /dev/null

# alpine:tcl:
#   stage: triggers
#   except:
#     - tags
#   before_script:
#     - apk add --update --no-cache curl
#   script:
#     - curl -X POST -F token=$CI_BUILD_TOKEN -F ref=master https://gitlab.timmertech.nl/api/v4/projects/47/trigger/pipeline > /dev/null
