image: registry.timmertech.nl/docker/docker:latest


stages:
  - build
  - trigger


variables:
  CI: 'true'
  DOCKER_DRIVER: overlay2


################################################################################
# Template(s)
################################################################################
.build:
  stage: build
  variables:
    DOCKER_FILE: Dockerfile
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  before_script:
    - echo "${CI_DEPENDENCY_PROXY_PASSWORD}" | docker login -u "${CI_DEPENDENCY_PROXY_USER}" --password-stdin "${CI_DEPENDENCY_PROXY_SERVER}"
    - echo ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - docker build --pull
        --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
        --build-arg VCS_REF="${CI_COMMIT_SHORT_SHA}"
        --build-arg CI_PROJECT_NAME=${CI_PROJECT_NAME}
        --build-arg CI_PROJECT_URL="${CI_PROJECT_URL}"
        --build-arg DOCKER_IMAGE=${DOCKER_IMAGE}
        --file=${DOCKER_FILE}
        --tag=${DOCKER_IMAGE} .


################################################################################
# Job Configuration
################################################################################
release:
  extends: .build
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_TAG}
  only:
    - tags
  after_script:
    - docker push ${DOCKER_IMAGE}


update:
  extends: .build
  only:
    - master
    - schedules
  after_script:
    - docker push ${DOCKER_IMAGE}


docker.hub:
  stage: trigger
  only:
    - tags
    - schedules
  script:
    - curl -s -H -X POST ${DOCKERHUB_TRIGGER} > /dev/null


# EOF