# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
include:
  - component: $CI_SERVER_FQDN/templates/components/workflow/default@0.1.1
  - component: $CI_SERVER_FQDN/templates/components/publish/live@0.3.0
  - component: $CI_SERVER_FQDN/templates/components/publish/hub@0.3.0

  # multi/latest
  - component: $CI_SERVER_FQDN/templates/components/docker/multi@1.1.0
    inputs:
      args: >-
        --cache-from=type=registry,ref=$HARBOR_REGISTRY_CACHE/docker/alpine-base-service:amd64
        --cache-from=type=registry,ref=$HARBOR_REGISTRY_CACHE/docker/alpine-base-service:arm64
      tag: $DOCKER_IMAGE_PATH:edge
      tags: >-
        --tag=$DOCKER_IMAGE_HUB_PATH:edge
      healthcheck-uuid: c17e32cd-aba0-4045-a511-b81b63af1649

  # multi/3.18
  - component: $CI_SERVER_FQDN/templates/components/docker/multi@1.1.0
    inputs:
      name: "multiarch:3.18"
      dockerfile: Dockerfile.318
      cache: false
      tag: $DOCKER_IMAGE_PATH:3.18
      tags: >-
        --tag=$DOCKER_IMAGE_HUB_PATH:3.18

  # multi/3.19
  - component: $CI_SERVER_FQDN/templates/components/docker/multi@1.1.0
    inputs:
      name: "multiarch:3.19"
      dockerfile: Dockerfile.319
      cache: false
      tag: $DOCKER_IMAGE_PATH:3.19
      tags: >-
        --tag=$DOCKER_IMAGE_HUB_PATH:3.19

  # multi/3.20
  - component: $CI_SERVER_FQDN/templates/components/docker/multi@1.1.0
    inputs:
      name: "multiarch:3.20"
      dockerfile: Dockerfile.320
      cache: false
      tag: $DOCKER_IMAGE_PATH:3.20
      tags: >-
        --tag=$DOCKER_IMAGE_HUB_PATH:3.20
