# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
include:
  - project: templates/ci
    file: default.yml

variables:
  UPSTREAM_IMAGE: registry.timmertech.nl/docker/alpine-base-service

.build:
  stage: build
  extends: .docker-build-amd64
  variables:
    DOCKER_BUILDX_JOB: $CI_JOB_ID
    DOCKER_PROXY: "ENABLED"
    DOCKER_HUB: "ENABLED"

build:
  extends: .build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "schedule"
  variables:
    DOCKER_IMAGE_CACHE_FROM: ${DOCKER_IMAGE_CACHE}
    DOCKER_IMAGE_CACHE_TO: ${DOCKER_IMAGE_CACHE}
    DOCKER_ARGS: >-
      --cache-from=type=registry,ref=${UPSTREAM_IMAGE}/cache:latest
      --cache-from=type=registry,ref=${UPSTREAM_IMAGE}/cache:amd64
      --build-arg=DOCKER_IMAGE_BASE=${UPSTREAM_IMAGE}:latest
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_PATH}:latest
      --tag=${DOCKER_IMAGE_HUB_PATH}:latest
    HEALTH_CHECK_UUID: c17e32cd-aba0-4045-a511-b81b63af1649

release:
  extends: .build
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    DOCKER_IMAGE: ${DOCKER_IMAGE_PATH}:${CI_COMMIT_TAG}
    DOCKER_BUILDX_CACHE_ENABLED: 0
    DOCKER_ARGS: >-
      --cache-from=type=registry,ref=${UPSTREAM_IMAGE}:latest
      --build-arg=DOCKER_IMAGE_BASE=${UPSTREAM_IMAGE}:latest
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:${CI_COMMIT_TAG}
