variables:
  REPOSITORY: registry.timmertech.nl

stages:
  - build
  - triggers
  
build:latest:
  stage: build
  only: 
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${REPOSITORY}
    - docker build --pull --force-rm=true 
        --build-arg VCS_REF=`git rev-parse --short HEAD` 
        --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` 
        --tag=${REPOSITORY}/${CI_PROJECT_PATH} .
    - docker push ${REPOSITORY}/${CI_PROJECT_PATH}

build:release:
  stage: build
  only:
    - tags
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${REPOSITORY}
    - docker build --pull --force-rm=true 
        --build-arg VCS_REF=`git rev-parse --short HEAD` 
        --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` 
        --tag=${REPOSITORY}/${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME} .
    - docker push ${REPOSITORY}/${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}

alpine:golang:
  stage: triggers
  except:
    - tags
  script:
    - curl -X POST -F token=a4d1a79e73cbcb71b14e343786de3a -F ref=master https://gitlab.timmertech.nl/api/v3/projects/19/trigger/builds > /dev/null

alpine:tcl:
  stage: triggers
  except:
    - tags
  script:
    - curl -X POST -F token=1f4f1e04d28e03c5617fb1ff372d1d -F ref=master https://gitlab.timmertech.nl/api/v4/projects/47/trigger/pipeline > /dev/null
   
gitlab:runner:latest:
  stage: triggers
  except:
    - tags
  script:
    - curl -X POST -F token=0a1b3b7f64d4526e9fc771eebf5b23 -F ref=master https://gitlab.timmertech.nl/api/v3/projects/20/trigger/builds > /dev/null

gitlab:runner:synology:
  stage: triggers
  except:
    - tags
  script:
    - curl -X POST -F token=0a1b3b7f64d4526e9fc771eebf5b23 -F ref=synology https://gitlab.timmertech.nl/api/v3/projects/20/trigger/builds > /dev/null
