# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
include:
  - project: templates/ci
    file: default.yml

.build:
  stage: build
  extends: .docker-build-amd64
  variables:
    DOCKER_PROXY: "ENABLED"

build:
  extends: .build
  variables:
    DOCKER_HUB: "ENABLED"
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_PATH}:latest
      --tag=${DOCKER_IMAGE_HUB_PATH}:latest
    HEALTH_CHECK_UUID: c17e32cd-aba0-4045-a511-b81b63af1649

release:
  extends: .build
  variables:
    DOCKER_HUB: "ENABLED"
    DOCKER_IMAGE: ${DOCKER_IMAGE_PATH}:${CI_COMMIT_TAG}
    DOCKER_ARGS: >-
      --cache-from=type=registry,ref=registry.timmertech.nl/docker/alpine-base:latest
      --cache-from=type=registry,ref=${DOCKER_IMAGE}
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:${CI_COMMIT_TAG}
  only:
    - tags
