image: registry.timmertech.nl/docker/docker:latest

stages:
  - build
  - deploy
  - trigger

include:
  - project: templates/ci
    file: docker.yml
  - project: templates/ci
    file: docker-hub.yml

################################################################################
# Template(s)
################################################################################
.build:
  stage: build
  interruptible: true
  script:
    - docker build --pull
      --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
      --build-arg VCS_REF="${CI_COMMIT_SHORT_SHA}"
      --build-arg CI_PROJECT_NAME=${CI_PROJECT_NAME}
      --build-arg CI_PROJECT_URL="${CI_PROJECT_URL}"
      --build-arg DOCKER_IMAGE=${DOCKER_IMAGE}
      --file=${DOCKER_FILE}
      --tag=${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}

################################################################################
# Job Configuration
################################################################################
build:
  extends: .build
  only:
    - main
    - schedules

dockerhub:
  stage: deploy
  extends: .dockerhub
  variables:
    DOCKERHUB_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest
  only:
    - main
    - schedules

release:
  extends: .build
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_TAG}
  only:
    - tags

dockerhub-release:
  stage: deploy
  extends: .dockerhub
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_TAG}
    DOCKERHUB_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}
  only:
    - tags

alpine.gitlab-runner:
  stage: trigger
  only:
    - main
    - schedules
  trigger:
    forward:
      yaml_variables: false
      pipeline_variables: false
    project: docker/gitlab-runner
